### ISSUE TITLE
Server - waiting lists

### ISSUE THREAD

**Issue by alina-lapina** [chrfrenning/upgraded-umbrella#13]
# FIFO
Each of the servers in different geographical zones maintain their own zone-specific waiting list. 
The servers have a FIFO policy for executing the client requests in the waiting list.

### Discussion 1
What data structure to use, why, document decision. 
Suggestion: Queue.java, all functionality is provided by jdk.

### Discussion 2
Do we want to have configurable amount of queue slots or simply hard code 18?

## Initialise waiting list
When the server started, the list is empty.

## Add to waiting list
If the server is already in the execution mode, the new incoming task will be added to the waiting list.

### Discussion 3
Remove when the task is pulled OR when performed?
Document the decision.

# Endpoint for last balancer to call when asked for the current load
### Discussion 4
Name for the endpoint? Suggestion `int currentLoad()`.
Respond with the current amount of tasks in the queue. No incoming parameters required.

# Thread spec
b. Adding new incoming tasks to the waiting list should not be delayed due to server being in execution mode.
c. You can implement different threads to isolate the waiting list and execution mode of servers. However, the server execution will take place in one single thread.
i. In other words, each server will have 2 threads. One for executing the tasks on top of the waiting list and one to accept new tasks from the client.

# Unit tests

**Comment by chrfrenning** [comment]
Implemented today in workshop, done.
