### ISSUE TITLE
Service impl - Parse dataset

### ISSUE THREAD

**Issue by alina-lapina** [chrfrenning/upgraded-umbrella#2]
# Dataset info
The servers will have access to a database consisting of the statistics dataset. The dataset is available for download from the course website in a single zip archive named `statistics_IN5020`.
The dataset contains information about 140,574 different cities in the world. 

For more information about the datasets refer the following website: https://public.opendatasoft.com/explore/dataset/geonames-all-cities-with-a-population-1000/.
The sample representation of the dataset is given below:
```
Geoname ID Name Country Code Country name EN Population Timezone Coordinates
2798301 Fleron BE Belgium 15994 Europe/Brussels 50.61516,5.68062
2798438 Fauvillers BE Belgium 1952 Europe/Brussels 49.85116,5.66405
2798581 Ettelgem BE Belgium 1181 Europe/Brussels 51.17984,3.02919
2798615 Essen BE Belgium 10000 Europe/Brussels 51.46791,4.46901
2798680 Erondegem BE Belgium 1742 Europe/Brussels 50.94118,3.95611
2798868 Eksaarde BE Belgium 6005 Europe/Brussels 51.14876,3.96814
2798949 Eghezee BE Belgium 14352 Europe/Brussels 50.59076,4.91175
```
The service you will implement is responsible for parsing the dataset and providing clients with
statistics information about different countries. The clients, using remote invocations, can ask
the query server for different information it requires.

# Parse dataset
The server parses the whole dataset every time a request is made. The server will have to read the complete dataset to answer the client’s query. (Make call to the 

# Output file
The client should name the output file as naive_server.txt. Each entry in the output file should correspond to a query from the input file

# Error handling

# Unit tests

**Comment by chrfrenning** [comment]
Fixed in earlier commit
