### ISSUE TITLE
Client - input file and remote invocation

### ISSUE THREAD

**Issue by alina-lapina** [chrfrenning/upgraded-umbrella#4]
# Input file
The client code will parse an input file containing a sequence of queries. 
Each line specifies a method name and an argument that should be invoked on the remote server. 
The input file will be provided at the course website. 

Input file format: `<method name> <arg1> <arg2> <arg3> <zone:#>`
a. The method name describes one of the 4 interfaces that server provides. Depending on the method, it can take up to 3 arguments as input. The Zone:# describes the Zone of the Server to which the request must sent to.
b. eg:- getPopulationofCountry United States Zone:1
c. eg:- getNumberofCities Norway 568422 Zone:4
d. eg:- getNumberofCountries 3 1616894 Zone:5
e. eg:- getNumberofCountries 6 1677496 4406235 Zone:4

# Error handling
Wrong format.
No file.

# Unit tests

**Comment by chrfrenning** [comment]
Fixed.
