### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by alina-lapina** [chrfrenning/upgraded-umbrella#6]
# Turnaround time 
(from the moment a client gets to one of the servers in each zone until it receives the final response)
# Execution time 
(from the moment a server starts running the request until it finds the response)
# Waiting time 
(from the moment a server gets the request on waiting list until it starts to get executed)

# Discussion
Communicate metrics?

**Comment by chrfrenning** [comment]
Think this is already solved now and return in the Result object
